"""add inviter_email to invites

Revision ID: 008335066615
Revises: efb82ce36653
Create Date: 2025-11-27 10:33:32.353327

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "008335066615"
down_revision: str | Sequence[str] | None = "efb82ce36653"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("invites", sa.Column("inviter_email", sa.String(length=320), nullable=False))
    op.alter_column("users", "supabase_user_id", existing_type=sa.UUID(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "supabase_user_id", existing_type=sa.UUID(), nullable=True)
    op.drop_column("invites", "inviter_email")
    # ### end Alembic commands ###
