"""Add timezone to the users table


Revision ID: 694e5c1086ac
Revises: f03ec8effab6
Create Date: 2025-11-28 08:58:46.595436

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "694e5c1086ac"
down_revision: str | Sequence[str] | None = "f03ec8effab6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("time_zone", sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "time_zone")
    # ### end Alembic commands ###
