"""add last_overlap_notified_at to relationships

Revision ID: 8564dfb5f107
Revises: cd38511288b1
Create Date: 2026-05-14 23:32:52.811961

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8564dfb5f107"
down_revision: str | Sequence[str] | None = "cd38511288b1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "relationships",
        sa.Column("last_overlap_notified_at", sa.DateTime(timezone=True), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("relationships", "last_overlap_notified_at")
    # ### end Alembic commands ###
