"""add notification_opt_outs table

Revision ID: 9f9d920ddd70
Revises: 8564dfb5f107
Create Date: 2026-05-14 23:41:31.257770

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9f9d920ddd70"
down_revision: str | Sequence[str] | None = "8564dfb5f107"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "notification_opt_outs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("key", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "key", name="uniq_notification_opt_out"),
    )
    op.create_index(
        "ix_notification_opt_outs_user_id", "notification_opt_outs", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_notification_opt_outs_user_id", table_name="notification_opt_outs")
    op.drop_table("notification_opt_outs")
    # ### end Alembic commands ###
