"""Add avatar_path to the user table

Revision ID: c6b10bd8e7cf
Revises: 694e5c1086ac
Create Date: 2025-12-05 16:05:42.700219

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c6b10bd8e7cf"
down_revision: str | Sequence[str] | None = "694e5c1086ac"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("avatar_path", sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "avatar_path")
    # ### end Alembic commands ###
