"""add relationship invites table

Revision ID: d567e5d039e8
Revises: 7d95549329d5
Create Date: 2025-09-14 14:53:35.342541

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "d567e5d039e8"
down_revision: str | Sequence[str] | None = "7d95549329d5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Reuse existing Postgres ENUM for member_role; create a new one for invite_status
member_role_enum = postgresql.ENUM("partner", "admin", name="member_role", create_type=False)
invite_status_enum = postgresql.ENUM(
    "pending", "accepted", "declined", "revoked", "expired", name="invite_status", create_type=False
)


def upgrade() -> None:
    """Upgrade schema."""
    bind = op.get_bind()
    # Create only the new enum; member_role already exists
    invite_status_enum.create(bind, checkfirst=True)
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "invites",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("token", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("relationship_id", sa.Integer(), nullable=True),
        sa.Column("inviter_user_id", sa.Integer(), nullable=True),
        sa.Column("invitee_user_id", sa.Integer(), nullable=True),
        sa.Column("invitee_email", sa.String(length=320), nullable=False),
        sa.Column("role", member_role_enum, nullable=False),
        sa.Column("status", invite_status_enum, nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("accepted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["invitee_user_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["inviter_user_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["relationship_id"], ["relationships.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token"),
    )
    op.create_index("ix_invites_expires_at", "invites", ["expires_at"], unique=False)
    op.create_index("ix_invites_invitee_email", "invites", ["invitee_email"], unique=False)
    op.create_index(op.f("ix_invites_status"), "invites", ["status"], unique=False)
    op.create_index(
        "ix_invites_unique_pending_per_relationship_email",
        "invites",
        ["relationship_id", "invitee_email"],
        unique=True,
        postgresql_where=sa.text("status = 'pending'"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_invites_unique_pending_per_relationship_email",
        table_name="invites",
        postgresql_where=sa.text("status = 'pending'"),
    )
    op.drop_index(op.f("ix_invites_status"), table_name="invites")
    op.drop_index("ix_invites_invitee_email", table_name="invites")
    op.drop_index("ix_invites_expires_at", table_name="invites")
    op.drop_table("invites")
    invite_status_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
