"""remove pending from relationship status

Revision ID: f03ec8effab6
Revises: 008335066615
Create Date: 2025-11-27 17:04:14.461022

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "f03ec8effab6"
down_revision: str | Sequence[str] | None = "008335066615"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
